### ISSUE TITLE
How to disable translation?

### ISSUE THREAD

**Issue by azulkipli** [AsgardCms/Translation#12]
For single language website, how to disable translation?

**Comment by nWidart** [comment]
Hi,

You can first remove the locale from the url by setting this setting to true: https://github.com/AsgardCms/Platform/blob/develop/config/laravellocalization.php#L33
Followed by removing the `Translatable` trait , Translation model, its migrations etc.
You can check https://github.com/dimsav/laravel-translatable for more information on that

**Comment by azulkipli** [comment]
Thanks, for current need it works.
How about put this setting to database so we can enable/disable this feature via backend setting?
