### ISSUE TITLE
Enabled new language string not appear at backend/translation/translations

### ISSUE THREAD

**Issue by azulkipli** [AsgardCms/Translation#13]
After I enable new language (Indonesian) at backend/setting/settings/core, 
![asgard_setting](https://cloud.githubusercontent.com/assets/8231792/12035177/8326f6e4-ae6c-11e5-9a29-dfc4793f4074.png)

the "core::core::tab.indonesian" string not appear in backend/translation/translations

![asgard_lang](https://cloud.githubusercontent.com/assets/8231792/12035123/0932ac20-ae6c-11e5-9f26-908ff6a9bf66.png)

I've already cleared translation cache.

**Comment by nWidart** [comment]
That's normal. You need to add the translation in the core.tab area as you see.

**Comment by azulkipli** [comment]
I dont understand. how to add the string, could you give me example?

**Comment by nWidart** [comment]
For example this pull requests adds a language: https://github.com/AsgardCms/Translation/pull/16
